name: Wakatime Readme Stats

on:
  workflow_dispatch:
  schedule:
    # Updates every 12 hours
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: Update Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
